---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ kapi_service_name }}-health'
    consul_services:
      - name: '{{ kapi_service_name }}-health'
        tags: []
        checks:
          - id: '{{ kapi_service_name }}-health'
            name: 'Lido Key API health'
            type: 'http'
            http: 'http://localhost:{{ kapi_port }}/health'